export const options = [{
    label: "序号",
    props: "goodsId",
    width: "auto",
    align: "left",
    show: true,
    fixed: true,
  },
  {
    label: "机构代码",
    props: "email",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "机构名",
    props: "goodsname",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "商品名称",
    props: "address",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "商品条码",
    props: "content",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "规格",
    props: "sku",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "品牌",
    props: "address",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "销售数量",
    props: "number",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "剩余库存",
    props: "address",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "成本价",
    props: "content",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
  {
    label: "成本金额",
    props: "amount",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
  },
];